name: Example
on:
    push:
        branches:
        - main

jobs:
  Run basic check:
    name: python
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install uv
        uses: astral-sh/setup-uv@v4

      - name: "Set up Python"
        uses: actions/setup-python@v5
        with:
          python-version-file: "pyproject.toml"

      - name: "Run ruff"
        run: |
          uv tool run ruff check 
          
