[project]
name = "pdf-toolkit"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12.4"
dependencies = [
    "pypdf4>=1.27.0",
]

[dependency-groups]
dev = [
    "ruff>=0.8.3",
]
